pipeline {
    agent any

    tools {
      nodejs 'NodeJS 4.8.6'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'cd nt-health;npm install'
            }
            }

        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'cd nt-health;npm test'
            }
        }
        stage('Package') {
            steps {
                echo 'Packaging....'
                sh 'cd nt-health;npm run build'
                archiveArtifacts artifacts: '**/distribution/*.zip', fingerprint: true
            }
        }
    }
}
